name: Daily Panchang Update

on:
  schedule:
    - cron: "30 18 * * *"   # भारतात रात्री 12:00 IST ला चालतो
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install node-fetch
        run: npm install node-fetch

      - name: Run update script
        run: node update/update.js

      - name: Commit updated Panchang
        run: |
          git config user.name "Panchang Auto Bot"
          git config user.email "bot@example.com"
          git add panchang.json
          git commit -m "Daily Panchang Update"
          git push
